export interface MetricContract {
  key: string;
  title: string;
  domain: 'growth' | 'finance' | 'product' | 'ops' | 'shared';
  kind: 'metric' | 'action';
  definition: string;
  formula: string;
  grain: string;
  sourceOfTruth: string[];
  owner: string;
  approver: string;
  onCall: string;
  instrumentation: string;
  status: 'governed' | 'draft' | 'deprecated';
  certification: 'certified' | 'provisional' | 'review_required';
  hasTests: boolean;
  sla: string;
  freshnessSlo: string;
  dataQualitySlo: string;
  testPassRate: string;
  lineage: string;
  runbook: string;
  agentActions: string[];
  lastRefreshedAt: string;
  version: string;
  updatedAt: string;
}

export const METRIC_CONTRACTS: Record<string, MetricContract> = {
  'growth_actions.pending_tasks': {
    key: 'growth_actions.pending_tasks',
    title: 'Pending Tasks',
    domain: 'growth',
    kind: 'metric',
    definition: 'Count of queued growth tasks that are still pending intervention.',
    formula: "count(*) where task_status = 'pending'",
    grain: 'task snapshot',
    sourceOfTruth: ['gtm.growth_task_queue'],
    owner: 'Growth Ops',
    approver: 'Data Platform',
    onCall: '#growth-ops-oncall',
    instrumentation: 'Generated from signal-to-task routing logic in growth_task_queue model.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 08:00 UTC',
    dataQualitySlo: 'Nulls < 0.1%, row-count drift < 10%',
    testPassRate: '99.5% (30d)',
    lineage: 'silver.stg_gtm_leads -> gtm.signal_trial_conversion_risk_daily -> gtm.growth_task_queue',
    runbook: '/docs/standards#incident-response-and-runbooks',
    agentActions: ['send_first_reachout', 'queue_11labs_call'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'growth_actions.urgent_tasks': {
    key: 'growth_actions.urgent_tasks',
    title: 'Urgent Tasks',
    domain: 'growth',
    kind: 'metric',
    definition: 'Pending growth tasks with urgent priority classification.',
    formula: "count(*) where task_status = 'pending' and priority = 'urgent'",
    grain: 'task snapshot',
    sourceOfTruth: ['gtm.growth_task_queue'],
    owner: 'Growth Ops',
    approver: 'Data Platform',
    onCall: '#growth-ops-oncall',
    instrumentation: 'Priority derived from signal_score threshold bands.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 08:00 UTC',
    dataQualitySlo: 'Threshold policy coverage = 100%',
    testPassRate: '99.2% (30d)',
    lineage: 'gtm.cfg_signal_thresholds -> gtm.growth_task_queue',
    runbook: '/docs/standards#data-quality-and-reliability-slos',
    agentActions: ['escalate_to_human_owner', 'prioritize_outreach'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'growth_actions.call_candidates': {
    key: 'growth_actions.call_candidates',
    title: '11Labs Call Candidates',
    domain: 'growth',
    kind: 'action',
    definition: 'Pending tasks recommended for immediate automated call outreach.',
    formula: "count(*) where recommended_channel = '11labs_call'",
    grain: 'task snapshot',
    sourceOfTruth: ['gtm.growth_task_queue', 'gtm.signal_trial_conversion_risk_daily'],
    owner: 'Growth',
    approver: 'Growth Ops',
    onCall: '#growth-automation-oncall',
    instrumentation: 'Recommended channel is assigned from signal score policy.',
    status: 'draft',
    certification: 'provisional',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 08:00 UTC',
    dataQualitySlo: 'Signal score bounds must pass 100%',
    testPassRate: '97.8% (30d)',
    lineage: 'silver.stg_gtm_leads -> gtm.signal_trial_conversion_risk_daily -> gtm.growth_task_queue',
    runbook: '/docs/metrics-governance#metric-change-workflow',
    agentActions: ['queue_11labs_call', 'create_task_comment'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'growth_actions.open_pipeline': {
    key: 'growth_actions.open_pipeline',
    title: 'Open Pipeline',
    domain: 'finance',
    kind: 'metric',
    definition: 'Dollar value of opportunities not in closed_won or closed_lost stage.',
    formula: "sum(amount_usd) for opportunities where stage not in ('closed_won','closed_lost')",
    grain: 'daily snapshot',
    sourceOfTruth: ['gtm.gtm_pipeline_snapshot'],
    owner: 'Growth + Finance',
    approver: 'Finance Analytics',
    onCall: '#finance-data-oncall',
    instrumentation: 'Computed from GTM opportunities staging models.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 09:00 UTC',
    dataQualitySlo: 'Stage mapping completeness = 100%',
    testPassRate: '99.7% (30d)',
    lineage: 'silver.stg_gtm_opportunities -> gtm.gtm_pipeline_snapshot',
    runbook: '/docs/sources-of-truth#finance',
    agentActions: ['notify_pipeline_risk', 'route_to_revops'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'growth_actions.lead_conversion': {
    key: 'growth_actions.lead_conversion',
    title: 'Lead Conversion Rate',
    domain: 'growth',
    kind: 'metric',
    definition: 'Share of leads that have reached converted state.',
    formula: '(leads_converted / leads_total) * 100',
    grain: 'daily snapshot',
    sourceOfTruth: ['gtm.gtm_pipeline_snapshot'],
    owner: 'Growth',
    approver: 'Growth Analytics',
    onCall: '#growth-analytics-oncall',
    instrumentation: 'Lead lifecycle states originate in GTM lead instrumentation.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 08:00 UTC',
    dataQualitySlo: 'Lifecycle state enum coverage = 100%',
    testPassRate: '99.1% (30d)',
    lineage: 'silver.stg_gtm_leads -> gtm.gtm_pipeline_snapshot',
    runbook: '/docs/instrumentation#identity-and-event-standards',
    agentActions: ['trigger_reengagement_sequence', 'assign_sdr_followup'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'growth_actions.signal_task_queue': {
    key: 'growth_actions.signal_task_queue',
    title: 'Signal Task Queue',
    domain: 'growth',
    kind: 'action',
    definition: 'Operational queue of growth interventions generated from risk signals.',
    formula: 'Signal score threshold filtering + prioritization policy',
    grain: '1 row per task',
    sourceOfTruth: ['gtm.growth_task_queue', 'gtm.cfg_signal_thresholds', 'gtm.signal_trial_conversion_risk_daily'],
    owner: 'Growth Ops',
    approver: 'Data Platform',
    onCall: '#growth-ops-oncall',
    instrumentation: 'Queue model materializes daily and is consumed by action systems.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 08:00 UTC',
    dataQualitySlo: 'Threshold enforcement failures = 0',
    testPassRate: '99.9% (30d)',
    lineage: 'silver.stg_gtm_leads -> gtm.signal_trial_conversion_risk_daily -> gtm.growth_task_queue',
    runbook: '/docs/standards#incident-response-and-runbooks',
    agentActions: ['create_growth_task', 'auto_assign_owner', 'trigger_reachout'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'growth_actions.pipeline_snapshot': {
    key: 'growth_actions.pipeline_snapshot',
    title: 'Pipeline Snapshot',
    domain: 'growth',
    kind: 'metric',
    definition: 'Current-state summary of leads and opportunities used for GTM planning.',
    formula: 'Aggregated snapshot from GTM lead/opportunity states',
    grain: '1 row per day',
    sourceOfTruth: ['gtm.gtm_pipeline_snapshot'],
    owner: 'Growth',
    approver: 'Growth Analytics',
    onCall: '#growth-analytics-oncall',
    instrumentation: 'Built from staged GTM entities with normalized stage/status values.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 08:00 UTC',
    dataQualitySlo: 'Snapshot completeness > 99.9%',
    testPassRate: '99.6% (30d)',
    lineage: 'silver.stg_gtm_leads + silver.stg_gtm_opportunities -> gtm.gtm_pipeline_snapshot',
    runbook: '/docs/sources-of-truth#growth',
    agentActions: ['publish_daily_snapshot', 'detect_pipeline_drop'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'growth_actions.action_throughput_7d': {
    key: 'growth_actions.action_throughput_7d',
    title: 'Action Throughput (7d)',
    domain: 'ops',
    kind: 'metric',
    definition: 'Executed action volume grouped by type and status over last 7 days.',
    formula: 'count(*) grouped by action_type, status over executed_at >= now - 7 days',
    grain: 'action type x status',
    sourceOfTruth: ['gtm.action_log'],
    owner: 'Growth Ops',
    approver: 'Ops Analytics',
    onCall: '#ops-data-oncall',
    instrumentation: 'Every workflow execution should emit an action_log row.',
    status: 'draft',
    certification: 'review_required',
    hasTests: false,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 08:00 UTC',
    dataQualitySlo: 'Execution status enum coverage = 100%',
    testPassRate: '92.0% (30d)',
    lineage: 'workflow executions -> gtm.action_log',
    runbook: '/docs/metrics-governance#trust-tiers-and-certification',
    agentActions: ['report_action_backlog', 'create_incident_if_drop'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'growth_actions.lead_intake_trend': {
    key: 'growth_actions.lead_intake_trend',
    title: 'Lead Intake Trend (14d)',
    domain: 'growth',
    kind: 'metric',
    definition: 'Daily lead and opportunity funnel trend for recent GTM intake.',
    formula: 'Daily aggregates of leads created, qualified, converted, and opportunities created/closed',
    grain: '1 row per day',
    sourceOfTruth: ['gtm.gtm_funnel_daily'],
    owner: 'Growth',
    approver: 'Growth Analytics',
    onCall: '#growth-analytics-oncall',
    instrumentation: 'Derived from staged GTM entities and published in gtm.agg_funnel_daily.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 08:00 UTC',
    dataQualitySlo: 'Lead status mapping coverage = 100%',
    testPassRate: '99.4% (30d)',
    lineage: 'silver.stg_gtm_leads -> gtm.gtm_funnel_daily',
    runbook: '/docs/instrumentation#event-taxonomy-for-agentic-workflows',
    agentActions: ['detect_intake_spike', 'trigger_priority_triage'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'finance_actions.total_mrr': {
    key: 'finance_actions.total_mrr',
    title: 'Total MRR',
    domain: 'finance',
    kind: 'metric',
    definition: 'Total monthly recurring revenue across all active paying subscriptions.',
    formula: 'sum(monthly_price_usd) for active subscriptions',
    grain: 'daily snapshot',
    sourceOfTruth: ['fin.mrr'],
    owner: 'Finance Analytics',
    approver: 'Finance Lead',
    onCall: '#finance-data-oncall',
    instrumentation: 'Subscription state and plan price must be synced daily from billing source.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 09:00 UTC',
    dataQualitySlo: 'Active subscription mapping coverage = 100%',
    testPassRate: '99.6% (30d)',
    lineage: 'silver.stg_subscriptions + silver.stg_plans -> fin.mrr',
    runbook: '/docs/sources-of-truth#finance',
    agentActions: ['notify_mrr_drop', 'trigger_pricing_review'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'finance_actions.collection_rate_latest_month': {
    key: 'finance_actions.collection_rate_latest_month',
    title: 'Collection Rate (Latest Month)',
    domain: 'finance',
    kind: 'metric',
    definition: 'Percentage of invoiced amount realized in the most recent revenue month.',
    formula: '(realized_revenue_usd / gross_revenue_usd) * 100',
    grain: 'monthly',
    sourceOfTruth: ['fin.monthly_revenue'],
    owner: 'Finance Ops',
    approver: 'Finance Analytics',
    onCall: '#finance-ops-oncall',
    instrumentation: 'Invoice status transitions must map to paid/open counts in monthly_revenue.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 09:00 UTC',
    dataQualitySlo: 'Collection rate bounded between 0 and 100',
    testPassRate: '99.3% (30d)',
    lineage: 'silver.stg_invoices -> fin.monthly_revenue',
    runbook: '/docs/standards#incident-response-and-runbooks',
    agentActions: ['trigger_collections_playbook', 'assign_account_owner'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'finance_actions.open_invoices_12m': {
    key: 'finance_actions.open_invoices_12m',
    title: 'Open Invoices (12m)',
    domain: 'finance',
    kind: 'metric',
    definition: 'Total open invoice count summed across last 12 months.',
    formula: 'sum(open_invoice_count) over last 12 months',
    grain: '12-month rolling',
    sourceOfTruth: ['fin.monthly_revenue'],
    owner: 'Finance Ops',
    approver: 'Finance Analytics',
    onCall: '#finance-ops-oncall',
    instrumentation: 'Invoice open/paid states must stay consistent with billing ledger.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 09:00 UTC',
    dataQualitySlo: 'Open invoice count must be non-negative',
    testPassRate: '99.1% (30d)',
    lineage: 'silver.stg_invoices -> fin.monthly_revenue',
    runbook: '/docs/metrics-governance#trust-tiers-and-certification',
    agentActions: ['prioritize_collections_queue', 'flag_aging_invoices'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'finance_actions.budget_variance_latest_month': {
    key: 'finance_actions.budget_variance_latest_month',
    title: 'Budget Variance (Latest Month)',
    domain: 'finance',
    kind: 'metric',
    definition: 'Difference between allocated budget and actual spend for latest month.',
    formula: 'sum(budget_variance_usd) on latest budget_month',
    grain: 'monthly',
    sourceOfTruth: ['fin.finance_budget_vs_actual_monthly'],
    owner: 'Finance',
    approver: 'Finance Lead',
    onCall: '#finance-ops-oncall',
    instrumentation: 'Budget allocations and spend events must join at organization-month grain.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 09:00 UTC',
    dataQualitySlo: 'Budget + spend fields non-null for active org-months',
    testPassRate: '98.9% (30d)',
    lineage: 'core.dim_finance_departments + core.fct_finance_transactions ->fin.finance_budget_vs_actual_monthly',
    runbook: '/docs/sources-of-truth#finance',
    agentActions: ['alert_budget_overrun', 'open_finance_review_task'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'finance_actions.budget_utilization_latest_month': {
    key: 'finance_actions.budget_utilization_latest_month',
    title: 'Budget Utilization (Latest Month)',
    domain: 'finance',
    kind: 'metric',
    definition: 'Actual spend as a ratio of budget allocation for latest month.',
    formula: '(sum(actual_spend_usd) / sum(budget_allocated_usd)) * 100',
    grain: 'monthly',
    sourceOfTruth: ['fin.finance_budget_vs_actual_monthly'],
    owner: 'Finance',
    approver: 'Finance Lead',
    onCall: '#finance-ops-oncall',
    instrumentation: 'Budget and spend rollups must use identical month windows and org keys.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 09:00 UTC',
    dataQualitySlo: 'Utilization ratio bounded between 0 and 500%',
    testPassRate: '98.7% (30d)',
    lineage: 'core.dim_finance_departments + core.fct_finance_transactions ->fin.finance_budget_vs_actual_monthly',
    runbook: '/docs/standards#data-quality-and-reliability-slos',
    agentActions: ['escalate_overspend', 'recommend_cost_controls'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
  'finance_actions.budget_vs_actual_monthly': {
    key: 'finance_actions.budget_vs_actual_monthly',
    title: 'Budget vs Actual (Monthly)',
    domain: 'finance',
    kind: 'metric',
    definition: 'Monthly org-level budget allocation, actual spend, variance, and AP exposure.',
    formula: 'budget_allocated_usd - actual_spend_usd with utilization and variance ratios',
    grain: 'organization x month',
    sourceOfTruth: ['fin.finance_budget_vs_actual_monthly'],
    owner: 'Finance Analytics',
    approver: 'Finance Lead',
    onCall: '#finance-data-oncall',
    instrumentation: 'Spend components (card, reimbursement, bill payment) and adjustments are normalized per org-month.',
    status: 'governed',
    certification: 'certified',
    hasTests: true,
    sla: '<= 24h',
    freshnessSlo: 'Daily by 09:00 UTC',
    dataQualitySlo: 'Organization-month key uniqueness = 100%',
    testPassRate: '98.8% (30d)',
    lineage: 'core.fct_finance_transactions + core.fct_finance_reimbursements + core.fct_finance_bill_payments ->fin.finance_budget_vs_actual_monthly',
    runbook: '/docs/sources-of-truth#finance',
    agentActions: ['generate_budget_review_packet', 'route_to_department_owner'],
    lastRefreshedAt: '2026-03-02T00:00:00Z',
    version: 'v1',
    updatedAt: '2026-03-02',
  },
};

export function getMetricContract(key: string): MetricContract | null {
  return METRIC_CONTRACTS[key] || null;
}
